Accept handlers return closes #1704
eternnoir/pyTelegramBotAPI pull request #1706
Opened 2022-09-09 23:50 UTC by byehack

2022-09-10 09:57 UTC, coder2020official commented
Hi!
I'll investigate it and review ASAP. Thank you for pull request.

2022-09-10 11:03 UTC, coder2020official requested changes

2022-09-10 11:03 UTC, coder2020official commented on telebot/__init__.py
> +                    ret = None
Renaming this variable to result would be more appropriate
```suggestion
                    result = None
```
And other variables should be renamed as well.

2022-09-10 11:03 UTC, coder2020official commented on telebot/__init__.py
> +                        ret = handler['function'](message)
Don't forget applying result instead of ret to async as well

2022-09-10 11:03 UTC, coder2020official commented on telebot/handler_backends.py
> +class Continue:
Renaming this to ContinueHandling would be more appropriate.. What do you think?

2022-09-10 11:07 UTC, Badiboy commented
Also please update 
ret = 
to 
result = 
It's the general practice in this code.

2022-09-10 11:41 UTC, coder2020official commented
Thank you for fixing the requested changes. We are now discussing about it with badiboy. We will let you know about the further changes.

2022-09-17 09:47 UTC, coder2020official commented
After resolving #1722 , you will have to make little changes(we will notify you)

2022-09-17 09:47 UTC, coder2020official commented
Btw, thank you for contributing and your patience.

2022-09-25 15:18 UTC, coder2020official commented
#1722 was merged, can you take a look and adapt your code?

2022-09-30 18:24 UTC, coder2020official commented
You deleted branch.. can you recreate it?

2022-10-01 23:58 UTC, byehack commented
@coder2020official opened https://github.com/eternnoir/pyTelegramBotAPI/pull/1742

2022-10-01 23:58 UTC, closed without merging