Support ContinueHandling
eternnoir/pyTelegramBotAPI pull request #1742
Opened 2022-10-01 23:57 UTC by byehack

2022-10-02 07:05 UTC, Badiboy commented
![image](https://user-images.githubusercontent.com/5613421/193442296-44f18812-8587-4fae-b0a5-373dea99f2a1.png)

2022-10-02 07:06 UTC, Badiboy commented
![image](https://user-images.githubusercontent.com/5613421/193442325-47c85c4e-44bd-4524-983c-f1f513f7f140.png)

It is not the subject of your update.

2022-10-04 22:08 UTC, Badiboy commented
Looks fine now. 
@coder2020official ?

2022-10-07 16:11 UTC, coder2020official requested changes

2022-10-07 16:11 UTC, coder2020official commented on telebot/async_telebot.py
> +from telebot.asyncio_handler_backends import BaseMiddleware, CancelUpdate, SkipHandler, State, ContinueHandling
You forgot to create a duplicate of ContinueHandling for async

2022-10-09 08:18 UTC, Badiboy commented
@coder2020official 
Looks fine now.

2022-10-09 15:58 UTC, coder2020official requested changes

2022-10-09 15:58 UTC, coder2020official commented on telebot/handler_backends.py
> +    in handlers to continue process.
Add code block here, something like this:

```suggestion
    in handlers to continue process.
    
    .. code-block:: python3
        :caption: Example of using ContinueHandling

        @bot.message_handler(commands=['start'])
        def start(message):
            bot.send_message(message.chat.id, 'Hello World!')
            return ContinueHandling()
        
        @bot.message_handler(commands=['start'])
        def start2(message):
            bot.send_message(message.chat.id, 'Hello World2!')
    
```

Same with async one but with async syntax.

2022-10-09 15:58 UTC, coder2020official commented on telebot/__init__.py
> +from telebot.handler_backends import (
What about examples of this feature on async and sync for examples folder?

2022-10-09 18:36 UTC, byehack commented
@Badiboy @coder2020official 
You have access to edit this PR.
As I don't know how to do tasks below, I recommend you doing each task below then check mark them:


> * [ ]  Test
> * [ ]  Create example
> * [ ]  Document
> * [ ]  Bump new version

2022-10-10 06:41 UTC, Badiboy commented
@coder2020official I propose to finish this PR "as is". It is functionally done and waits too much. Other tests and documentation can be done via new PR...

2022-10-11 15:25 UTC, coder2020official commented
Ig that's it. Checked documentation - everything is fine.

2022-10-11 15:26 UTC, coder2020official approved these changes

2022-10-11 16:03 UTC, Badiboy commented
Come on, guys, let's go )

2022-10-11 16:03 UTC, merged

2022-10-11 16:04 UTC, coder2020official commented
Ура, бабахнули в мастер

Thanks for patience @byehack

2022-10-11 16:14 UTC, coder2020official commented
* Just a reminder that we have English chat:
* https://github.com/byehack/pyTelegramBotAPI/tree/ContinueHandling#the-telegram-chat-group