BOT API 7.2
eternnoir/pyTelegramBotAPI pull request #2208
Opened 2024-03-31 20:17 UTC by coder2020official

Not promising anything, let's see how far I can go.

Bot API 7.2

Integration with Business Accounts

- [x] Added the class [BusinessConnection](https://core.telegram.org/bots/api#businessconnection) and updates about the connection or disconnection of the bot to a business account, represented by the field business_connection in the class [Update](https://core.telegram.org/bots/api#update).

- [x] Added updates about new messages in a business account connected to the bot, represented by the field business_message in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added updates about message edits in a business account connected to the bot, represented by the field edited_business_message in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added updates about message deletion in a business account connected to the bot, represented by the class [BusinessMessagesDeleted](https://core.telegram.org/bots/api#businessmessagesdeleted) and the field deleted_business_messages in the class [Update](https://core.telegram.org/bots/api#update).
- [x] Added the method [getBusinessConnection](https://core.telegram.org/bots/api#getbusinessconnection).
Working on Behalf of Business Accounts

- [x] Added the parameter business_connection_id to the methods [sendMessage](https://core.telegram.org/bots/api#sendmessage), [sendPhoto](https://core.telegram.org/bots/api#sendphoto), [sendVideo](https://core.telegram.org/bots/api#sendvideo), [sendAnimation](https://core.telegram.org/bots/api#sendanimation), [sendAudio](https://core.telegram.org/bots/api#sendaudio), [sendDocument](https://core.telegram.org/bots/api#senddocument), [sendSticker](https://core.telegram.org/bots/api#sendsticker), [sendVideoNote](https://core.telegram.org/bots/api#sendvideonote), [sendVoice](https://core.telegram.org/bots/api#sendvoice), [sendLocation](https://core.telegram.org/bots/api#sendlocation), [sendVenue](https://core.telegram.org/bots/api#sendvenue), [sendContact](https://core.telegram.org/bots/api#sendcontact), [sendPoll](https://core.telegram.org/bots/api#sendpoll), [sendDice](https://core.telegram.org/bots/api#senddice), [sendGame](https://core.telegram.org/bots/api#sendgame), and [sendMediaGroup](https://core.telegram.org/bots/api#sendmediagroup).
- [ ] Added the parameter business_connection_id to the method [sendChatAction](https://core.telegram.org/bots/api#sendchataction).
- [ ] Added the field business_connection_id to the class [Message](https://core.telegram.org/bots/api#message).
- [ ] Added the field sender_business_bot to the class [Message](https://core.telegram.org/bots/api#message).
Information about Business Accounts

- [ ] Added the class [BusinessIntro](https://core.telegram.org/bots/api#businessintro) and the field business_intro to the class [Chat](https://core.telegram.org/bots/api#chat).
- [ ] Added the class [BusinessLocation](https://core.telegram.org/bots/api#businesslocation) and the field business_location to the class [Chat](https://core.telegram.org/bots/api#chat).
- [ ] Added the classes [BusinessOpeningHours](https://core.telegram.org/bots/api#businessopeninghours) and [BusinessOpeningHoursInterval](https://core.telegram.org/bots/api#businessopeninghoursinterval) and the field business_opening_hours to the class [Chat](https://core.telegram.org/bots/api#chat).
Mixed-Format Sticker Packs

- [ ] Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- [ ] Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
- [ ] Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- [ ] Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).
- [ ] Increased the maximum number of stickers in any regular and mask sticker set to 120.
- [ ] Allowed to upload WEBM stickers using [SendSticker](https://core.telegram.org/bots/api#sendsticker).
Request Chat Improvements

- [ ] Added the fields request_name, request_username, and request_photo to the class [KeyboardButtonRequestUsers](https://core.telegram.org/bots/api#keyboardbuttonrequestusers).
- [ ] Added the fields request_title, request_username, and request_photo to the class [KeyboardButtonRequestChat](https://core.telegram.org/bots/api#keyboardbuttonrequestchat).
- [ ] Added the class SharedUser and replaced the field user_ids in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.
- [ ] Added the fields title, username, and photo to the class [ChatShared](https://core.telegram.org/bots/api#chatshared).
Other Changes

- [ ] Added the field is_from_offline to the class [Message](https://core.telegram.org/bots/api#message).
- [ ] Added the field can_connect_to_business to the class [User](https://core.telegram.org/bots/api#user).
- [ ] Added the field personal_chat to the class [Chat](https://core.telegram.org/bots/api#chat).
- [ ] Added the method [replaceStickerInSet](https://core.telegram.org/bots/api#replacestickerinset),
- [ ] Added the class [Birthdate](https://core.telegram.org/bots/api#birthdate) and the field birthdate to the class [Chat](https://core.telegram.org/bots/api#chat).
- [ ] Added the field BiometricManager to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).

2024-03-31 20:56 UTC, coder2020official commented
- Skipping:
- Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
@badiboy they made stickerpacks mixed, meaning you can have both vids, photo stickers etc; now my brain is not braining regarding the actions to keep backward compatibility

2024-03-31 21:37 UTC, coder2020official commented
@badiboy done, need your opinion on 2 things; and your review

2024-03-31 21:52 UTC, Badiboy commented
Got it.

2024-04-02 21:41 UTC, Badiboy commented
@coder2020official 50% reviewed, mostly fine. Hope to finish tomorrow.

2024-04-04 21:24 UTC, Badiboy requested changes

2024-04-04 21:26 UTC, Badiboy commented
@coder2020official I propose to fix this issues and merge the PR. Then continue with 3 open questions mentioned in your main topic. To avoid long live of this huge update.

2024-04-04 21:28 UTC, coder2020official commented
And what are we gonna do about the things I skipped

2024-04-04 21:34 UTC, Badiboy commented
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/8ca0152e-c461-4409-aaef-1ebe511a0042)

2024-04-04 21:36 UTC, coder2020official commented
And can you answer my comment

2024-04-04 21:38 UTC, Badiboy commented
I did. Firstly we'll close this huge update. Then address other or non/closed items.

2024-04-04 21:42 UTC, coder2020official commented
Can't see your comment on your changes:
> Used, but not defined in SyncTelebot.
> What do you mean? I think I copied it from sync

2024-04-04 21:45 UTC, coder2020official commented on telebot/async_telebot.py
> +    def check_regexp_input(regexp, method_name):
What do you mean? I think I copied it from sync

2024-04-04 21:45 UTC, coder2020official commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
Btw, what do I set format to? 
> correspond to previous behaviour
I think previously only .png and .webp thumbnails were supported, can't remember though; what do I do

2024-04-04 21:45 UTC, coder2020official commented
Oops, I forgot to submit my comments. Check now

2024-04-04 21:46 UTC, Badiboy commented
> Can't see your comment on your changes:
> 
> > Used, but not defined in SyncTelebot.
> > What do you mean? I think I copied it from sync

You are right. I checked only in "modified" and it was not visible. Sorry.

2024-04-04 21:47 UTC, coder2020official commented
So I ignore your 2 comments?

2024-04-04 21:51 UTC, Badiboy commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
"None" as default parameter value.
"static" + deprecation warning - if the value is not passed

2024-04-04 21:51 UTC, coder2020official commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
got it

2024-04-04 21:53 UTC, Badiboy commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
If format is passed - use format.
elif is_animated=True - “animated” and deprecation warning
elif is_video=True - “video” and deprecation warning
else - “static” and deprecation warning

2024-04-04 21:56 UTC, coder2020official commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
but there are no such params?

2024-04-04 21:57 UTC, coder2020official commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
I think you were correct the first time

2024-04-04 22:03 UTC, Badiboy commented on telebot/__init__.py
> +        :param format: Format of the thumbnail, must be one of “static” for a .WEBP or .PNG image, “animated” for a .TGS animation, or “video” for a WEBM video
> but there are no such params?
Hmmm... Where I saw it... Oky then. Let's be static if undefined.

2024-04-04 22:12 UTC, coder2020official commented
I think I am done

2024-04-04 22:17 UTC, Badiboy commented
🤝 Let's merge and then go to remaining items.

2024-04-04 22:18 UTC, merged